### ISSUE TITLE
BGP version 11 is not compatible with Netbox version 3.7

### ISSUE THREAD

**Issue by dominik-hbs** [netbox-community/netbox-bgp#171]
**NetBox version**
3.7.0

**Describe the bug**
Hi, 

BGP version 11 is not compatible with Netbox version 3.7.

**Comment by 129828** [comment]
Adding to this, would it not be handy to not include a max_version? 
Seems like with every major update it spawns a ticket like this which only creates a PR with a single numeric change?
Or is it simply to prevent any compatibility issues?

**Comment by jeffgdotorg** [comment]
Closing as fixed:
- BGP plugin v0.12.x has been released and is compatible to NetBox v3.7.x.
- BGP plugin v0.13.2 is compatible to NetBox v4.0.x.
