### ISSUE TITLE
502 Bad Gateway in Netbox 3.7.0. 

### ISSUE THREAD

**Issue by HumlePung** [netbox-community/netbox-bgp#172]
**NetBox version**
3.7.0

**Describe the bug**
When netbox-bgp plugin is active, I get 502 Bad Gateway. When I disable the netbox-bgp plugin in the configuration.py file it works. I have other plugins that works fine. 

Have tried to uninstall the plugin and install it again, same problem. 

**To Reproduce**
To reproduce this for me I just enable the plugin. 

**Expected behavior**
To not get a 502 Bad Gateway

**Screenshots**
<img width="502" alt="bilde" src="https://github.com/k01ek/netbox-bgp/assets/68464234/90cb64da-f5ab-408c-bd38-deb63ef8c8b2">

**Comment by pl0xym0r** [comment]
I think that's the same issue as  #171 and PR #170  should solve it

**Comment by bails2047** [comment]
Please can someone update the repo as per PR#170 to include version 3.7 so we can run this in a Docker setup as this is causing our Netbox upgrade to 3.7 to fail each time as Docker will pull the latest version from github when building.

**Comment by ingvaldlorentzen** [comment]
Seeing as the only change in #170 is increasing `max_version` in the plugin, you can override it manually.
We are currently overriding the `max_version` after install in our Dockerfile:

`RUN sed -i 's/3.6.99/3.7.99/g' /opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py` 

It's not pretty, but it works as a temporary workaroun as we wait for a new version in PyPI with official support.

**Comment by bails2047** [comment]
Thanks for the response. The only issue is the netbox container won't load with the current version as the version checking that is in place after upgrading netbox to version 3.7 won't allow the container to start. 

Is this plugin downloaded and installed each time the container is spun up? We were looking to see if we could update the package locally, but it seems to be changed back to the original each time the container is spun up and we can't see anything on the Docker host where this might be stored.

Thanks for any assistance.

**Comment by ingvaldlorentzen** [comment]
Yes, you have to do the modification before starting the container.   
We extend the NetBox docker image, so we do it in the Dockerfile for our custom build. 

How to do this depends on your setup, if your are unsure how to achieve it I would recommend waiting for an official release. I just provided it as an option, if you feel comfortable poking around, I wouldn't really recommend it.
