### ISSUE TITLE
ERROR:  relation "netbox_bgp_community" already exists

### ISSUE THREAD

**Issue by lucatortiglione** [netbox-community/netbox-bgp#179]
Hi,
how can i resolve this problem ?

Operations to perform:
netbox-1               |   Apply all migrations: account, admin, auth, circuits, contenttypes, core, dcim, django_rq, extras, ipam, netbox_bgp, sessions, social_django, taggit, tenancy, users, virtualization, vpn, wireless
netbox-1               | Running migrations:
postgres-1             | 2024-01-31 11:25:25.669 UTC [33] ERROR:  relation "netbox_bgp_community" already exists
postgres-1             | 2024-01-31 11:25:25.669 UTC [33] STATEMENT:  CREATE TABLE "netbox_bgp_community" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created" date NULL, "last_updated" timestamp with time zone NULL, "number" integer NOT NULL CHECK ("number" >= 0), "status" varchar(50) NOT NULL, "description" varchar(200) NOT NULL, "value" varchar(64) NOT NULL, "role_id" bigint NULL, "site_id" bigint NULL, "tenant_id" bigint NULL)
netbox-1               | Traceback (most recent call last):
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
netbox-1               |     return self.cursor.execute(sql)
netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
netbox-1               |     raise ex.with_traceback(None)
netbox-1               | psycopg.errors.DuplicateTable: relation "netbox_bgp_community" already exists
netbox-1               | 
netbox-1               | The above exception was the direct cause of the following exception:
netbox-1               | 
netbox-1               | Traceback (most recent call last):
netbox-1               |   File "/opt/netbox/netbox/./manage.py", line 10, in <module>
netbox-1               |     execute_from_command_line(sys.argv)
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
netbox-1               |     utility.execute()
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
netbox-1               |     self.fetch_command(subcommand).run_from_argv(self.argv)
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
netbox-1               |     self.execute(*args, **cmd_options)
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
netbox-1               |     output = self.handle(*args, **options)
netbox-1               |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
netbox-1               |     res = handle_func(*args, **kwargs)
netbox-1               |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
netbox-1               |     post_migrate_state = executor.migrate(
netbox-1               |                          ^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
netbox-1               |     state = self._migrate_all_forwards(
netbox-1               |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
netbox-1               |     state = self.apply_migration(
netbox-1               |             ^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
netbox-1               |     state = migration.apply(state, schema_editor)
netbox-1               |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
netbox-1               |     operation.database_forwards(
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
netbox-1               |     schema_editor.create_model(model)
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 451, in create_model
netbox-1               |     self.execute(sql, params or None)
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 45, in execute
netbox-1               |     return super().execute(sql, params)
netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
netbox-1               |     cursor.execute(sql, params)
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
netbox-1               |     return self._execute_with_wrappers(
netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
netbox-1               |     return executor(sql, params, many, context)
netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
netbox-1               |     with self.db.wrap_database_errors:
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
netbox-1               |     raise dj_exc_value.with_traceback(traceback) from exc_value
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
netbox-1               |     return self.cursor.execute(sql)
netbox-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^
netbox-1               |   File "/opt/netbox/venv/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
netbox-1               |     raise ex.with_traceback(None)
netbox-1               | django.db.utils.ProgrammingError: relation "netbox_bgp_community" already exists
netbox-1               |   Applying netbox_bgp.0001_initial...
netbox-1 exited with code 1

**Comment by pl0xym0r** [comment]
netbox + plugin versions ?

**Comment by lucatortiglione** [comment]
Netbox 3.7.1 via docker
and latest version of netbox-bgp 0.12.0

**Comment by pl0xym0r** [comment]
would you mind sharing your dockerfile?

**Comment by lucatortiglione** [comment]
Give a look at
https://pastebin.com/JwmztipN

and

https://pastebin.com/tSBLh2gE

**Comment by pl0xym0r** [comment]
these are the docker compose, don't you build the image of netbox with plugins in it? thanks to a dockerfile?

**Comment by lucatortiglione** [comment]
> these are the docker compose, don't you build the image of netbox with plugins in it? thanks to a dockerfile? Howdo you install the plugins ?

I'm not very expert of Docker, i have just followed a guide.

Maybe the file is 
https://pastebin.com/2Rf2FT8f

Otherwise please tell me how the file is named

**Comment by pl0xym0r** [comment]
well, it seems you do not install the plugin into the image but on the configuration.py you enable it --> same as #84 

this is my dockerfile:

FROM netboxcommunity/netbox:v3.7.1
**RUN mkdir /opt/plugins
WORKDIR /opt/plugins
COPY netbox-bgp netbox-bgp
RUN /opt/netbox/venv/bin/python3 -m pip install netbox-bgp/.**
WORKDIR /opt/netbox/netbox
RUN SECRET_KEY="azertyuipmlkjhgfdsqwwxcvbnbvcxwqsdeazrgthyjukilomp" /opt/netbox/venv/bin/python /opt/netbox/netbox/manage.py collectstatic --no-input

dockerfile and netbox-bgp local repo are in the same folder
![image](https://github.com/k01ek/netbox-bgp/assets/148605740/b3f89dc9-9c96-474d-9ec6-4c8ded9aa9e2)

If you want to keep your dockerfile from https://github.com/netbox-community/netbox-docker  , just add the installation of the plugin into it, rebuild the image and launch it

**Comment by lucatortiglione** [comment]
My apologies, i'm a bit noob about docker,
what should i add to my dockerfile for installing the plugin into it ?

**Comment by pl0xym0r** [comment]
the 4 lines in bold on previous comment

**Comment by cruse1977** [comment]
Advice provided, seems a legacy issue
