### ISSUE TITLE
Expose BGP Sessions in Device data model

### ISSUE THREAD

**Issue by elipsion** [netbox-community/netbox-bgp#180]
**Is your feature request related to a problem? Please describe.**
When creating device configuration templates, I would like to also include BGP sessions.

**Describe the solution you'd like**
A data model relation for Device -> Session, not just the other way around.

**Describe alternatives you've considered**
Adding BGP sessions as a Custom Field to the Device data model object, and linking them manually.

**Comment by elipsion** [comment]
Found it using `nbshell`. The name `bgpsession_set` was not expected, to say the least.

**Comment by pl0xym0r** [comment]
As the documentation mentions https://github.com/netbox-community/netbox/blob/develop/docs/features/configuration-rendering.md , you can ask every class, including plugins.

From what I undertand on your needs, you could parse all sessions and filter by your device (as the relation session --> device exists), exemple:

{% for session in netbox_bgp.BGPSession.objects.all() %}
{% if session.device.name == device.name %}
session {{ session.name }}
{% endif%}
{% endfor %}

![image](https://github.com/k01ek/netbox-bgp/assets/148605740/d4563b92-599b-4777-8ff0-24f0854cadac)
![image](https://github.com/k01ek/netbox-bgp/assets/148605740/f028e6f1-8ac8-446b-ba19-f3d624d2c4dd)


I don't think you could get a relation device --> session as it's a plugin

**Comment by pl0xym0r** [comment]
Even this is quite easier and quickier :

{% for session in netbox_bgp.BGPSession.objects.filter(device=device) %}
session {{ session.name }}
{% endfor %}
