### ISSUE TITLE
Add key to ChoiceSets to allow user override of choices

### ISSUE THREAD

**Issue by cruse1977** [netbox-community/netbox-bgp#189]
**Is your feature request related to a problem? Please describe.**
In certain plugins and certain netbox choicesets themselves, users are able to override the choiceset via the FIELD_CHOICES variable in configuration.py. This is achieved by adding a 'key' attribute under the choiceset itself.

eg (from netbox-inventory):

```
class AssetStatusChoices(ChoiceSet):
    key = 'Asset.status'
    
 ```
meaning its then possible to reference (as per the example above) nb_inventory.Asset.status to override or add to the pre-configured choices.

**Describe the solution you'd like**
As above a key on BGPSessionStatus to allow configuration.py overrides and additional choices.  Note this should only apply where choices are descriptive 

**Describe alternatives you've considered**
n/a

**Additional context**

**Comment by natm** [comment]
https://linear.app/netboxlabs/issue/BIZ-3/

**Comment by cruse1977** [comment]
Completed in PR
