### ISSUE TITLE
DB Migration Issue - simialr to #108

### ISSUE THREAD

**Issue by cameronw1996** [netbox-community/netbox-bgp#195]
**NetBox version**
v3.7.1

**Plugin version**
v0.12.1

I think I have stumbled into the same issue as #108 - not sure how to get round it as the workarounds detail in #108 are not possible. 

Only last chance I think is to edit the DB directly. Thoughts?

**Comment by cruse1977** [comment]
I'm closing this as I've been unable to replicate and this is fairly old plugin version (and issue now).
