### ISSUE TITLE
Unable to get custom fields for peer groups via API (same as #183)

### ISSUE THREAD

**Issue by rvtipper** [netbox-community/netbox-bgp#201]
**NetBox version**
netbox: 4.0.8
netbox-bgp: 0.13.2

**Describe the bug**
I can't retrieve or set custom fields via API for peer groups

**To Reproduce**
Fetch any peer group via API, for this example custom fields values are already created and set via gui

```
GET /api/plugins/bgp/peer-group/34/

HTTP 200 OK
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "id": 34,
    "url": "http://localhost:7357/plugins/bgp/peer-group/34/",
    "display": "TEST_GROUP",
    "name": "TEST_GROUP",
    "description": "",
    "import_policies": [],
    "export_policies": [],
    "comments": ""
}
```

**Expected behavior**
To be able to see custom fields values, for example on a session I can see all

```
    "custom_fields": {
        "cluster": null,
        "local_preference": null,
        "prefix_limit": 10000,
        "prefix_threshold": 80,
        "prefix_threshold_log_only": true
    },
```

**Additional context**
Same as #183

**Comment by pl0xym0r** [comment]
It seems I forgot them on serializer during 4.0 migration, I'll fix it
