### ISSUE TITLE
Please add Netbox 4.1.XX support

### ISSUE THREAD

**Issue by VitMain** [netbox-community/netbox-bgp#205]
Please update plugin compatibility with the Netbox 4.1.XX. Right now, the plugin support max_version = '4.0.99'
Thank you!

**Comment by netravnen** [comment]
On a netbox test instance, you can validate the 4.1.x version compability. By hand editing the file `/opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py`.

```
# grep --perl-regex 'm(in|ax)_version =' /opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py
    min_version = '4.0.0'
    max_version = '4.0.99'
```

Or `sed --regexp-extended --expression='/max_version/s/4\.0\.[0-9]+/4.1.99/' --in-place /opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py`

**Comment by darkcloud784** [comment]
> On a netbox test instance, you can validate the 4.1.x version compability. By hand editing the file `/opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py`.
> 
> ```
> # grep --perl-regex 'm(in|ax)_version =' /opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py
>     min_version = '4.0.0'
>     max_version = '4.0.99'
> ```
> 
> Or `sed --regexp-extended --expression='/max_version/s/4\.0\.[0-9]+/4.1.99/' --in-place /opt/netbox/venv/lib/python3.11/site-packages/netbox_bgp/__init__.py`
> 
> Re-installing the package will overwrite any manual changes to the package files.

I think this is a good work around but still needs to be updated in the main branch so updates can be done seamlessly.

**Comment by cruse1977** [comment]
Hi, There needs to be a final 4.0 release first to fix the api issue - a 4.1 will follow

**Comment by netravnen** [comment]
https://github.com/netbox-community/netbox-bgp/pull/206

**Comment by aascedu** [comment]
> #206

sure but as long as they don't merge the PR we won't do much 😉

**Comment by cruse1977** [comment]
0.14.0

**Comment by VitMain** [comment]
Thank you!
