### ISSUE TITLE
Add Journaling to netbgp-bgp objects

### ISSUE THREAD

**Issue by rvtipper** [netbox-community/netbox-bgp#209]
**Describe the solution you'd like**
Seems like most objects in netbox (and some other plugins) have a Journal option along with the Changelog. This would be very useful in the BGP plugin. Use cases are to add context for non-standard route policies or add ticket numbers to prefix list changes etc. Hoping this is something you could inherit from netbox.

**Describe alternatives you've considered**
It's possible to document in confluence etc but it's perfect to have this directly accessible in the plugin itself.

thanks!

**Comment by pl0xym0r** [comment]
![image](https://github.com/user-attachments/assets/3241b693-9fba-45a4-b8ee-eafbeb47b551)
To implement it, HTML templates needs to be cleaned (remove tabs block as inherited) + use include(get_model_urls()) to inherit automatically from Changelog + jounal views in urls.py
@cruse1977 If ok, I'll do it

**Comment by cruse1977** [comment]
Thanks would be appreciated, am keen to look to expand on this plugin - the current plan is - final 4.0 release to address the api issue, then 4.1 release then circle back to some of the issues + PR's

**Comment by cruse1977** [comment]
Resolved in 0.13.3 and 0.14.0
