### ISSUE TITLE
GraphQL tests failing in v4.0.11

### ISSUE THREAD

**Issue by cruse1977** [netbox-community/netbox-bgp#214]
**NetBox version**
v4.0.11

**Describe the bug**

**To Reproduce**
1. cd develop
2. docker compose up
3. docker exec -it develop-netbox-1 /opt/netbox/netbox/manage.py test netbox_bgp

Significant failure occur around graphql

**Expected behavior**
Tests pass}

**Comment by pl0xym0r** [comment]
It doesn't surprise me as I didn't release them for 4.0
That's why I made #200 
Or am I missing something?

**Comment by cruse1977** [comment]
with #200 - Ran 205 tests in 2.560s

FAILED (failures=13)
Destroying test database for alias 'default'...

**Comment by pl0xym0r** [comment]
Hmmm ... strange, I would not make a PR if the test failed.
I did them without #204 , idk if it modifies the behavior

**Comment by cruse1977** [comment]
On which netbox version ?

**Comment by pl0xym0r** [comment]
At that time, I think I was on 4.0.7
