### ISSUE TITLE
Netbox plugin BGP directly on the panel

### ISSUE THREAD

**Issue by andretlemos** [netbox-community/netbox-bgp#215]
Hi, 

Is it possible to move netbox plugin bgp inside Plugin tab, to directly to Netbox menu as NetboxDNS you can see below?

![image](https://github.com/user-attachments/assets/81304676-c386-49f2-ad88-950047642926)

I think would be mucch better to see and get info for users.

Thanks in advanced.

**Comment by rvtipper** [comment]
There's a note in the readme how to do this under Configuration

> top_level_menu: Bool (default False) Enable top level section navigation menu for the plugin.
