### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kprklg** [netbox-community/netbox-bgp#221]
NetBox Community v4.1.4

cd /opt/netbox/netbox
source /opt/netbox/venv/bin/activate
pip install netbox-topology-views --upgrade
python3 manage.py collectstatic --no-input
python3 manage.py collectstatic
python3 manage.py migrate
python3 manage.py reindex --lazy

SystemCheckError: System check identified some issues:

ERRORS:
netbox_bgp.PrefixList.tags: (fields.E304) Reverse accessor 'Tag.prefixlist_set' for 'netbox_bgp.PrefixList.tags' clashes with reverse accessor for 'netbox_routing.PrefixList.tags'.
        HINT: Add or change a related_name argument to the definition for 'netbox_bgp.PrefixList.tags' or 'netbox_routing.PrefixList.tags'.
netbox_routing.PrefixList.tags: (fields.E304) Reverse accessor 'Tag.prefixlist_set' for 'netbox_routing.PrefixList.tags' clashes with reverse accessor for 'netbox_bgp.PrefixList.tags'.
        HINT: Add or change a related_name argument to the definition for 'netbox_routing.PrefixList.tags' or 'netbox_bgp.PrefixList.tags'.

![Screenshot 2024-10-18 165037](https://github.com/user-attachments/assets/59ee5347-41a2-44bc-a85f-442b63802ce1)

**Comment by cruse1977** [comment]
This is not a bug - netbox-routing uses the same model names as NetBox BGP so this is expected - you will need to choose one of the plugins.
