### ISSUE TITLE
Bulk edit is overwriting unchanged values

### ISSUE THREAD

**Issue by jwbensley** [netbox-community/netbox-bgp#227]
**NetBox version**
NetBox v3.7.8 with BGP plugin v0.12.1.

**Describe the bug**
When using the Bulk Edit feature on this plugin, it overwrites various fields.

**To Reproduce**

1. Here I select a bunch of BGP sessions with the same peer, and then click "Edit Selected":
![grafik](https://github.com/user-attachments/assets/3e84465d-6fb9-498c-a962-21444490aa9f)

1. The first issue that you can see if that "Status" has a value populated by default `Offline`, which is not the current status of any of these BGP sessions. If I click save I will now set all these BGP sessions to Offline. So this is the first bug in my opinion, a default value is set on the status field and it should be blank so that the status isn't changed for these BGP sessions unless I set a status value:
![grafik](https://github.com/user-attachments/assets/f66177e2-5c6f-4b33-a6c7-30959f06c59c)

1. The second issue is that one of the custom fields we use on BGP sessions is a JSON field. This may or may not be populated for the BGP sessions but, as you can see below, when using bulk edit the field is correctly displayed as empty. Like all fields, the expectation is that the value in this field would only be updated if I put something in here. If I leave it as it is and click save, this will set the value of this field on all BGP sessions being edited to null/empty, even though I didn't click the "set null" checkbox below. So writing nothing in this field is being interpreted as me actively setting the field to null, instead of relying on the "set null" checkbox below.
![grafik](https://github.com/user-attachments/assets/9ea3e552-4df8-4f7a-ba8f-dfec8eb7600e)

**Expected behavior**
1. The status field should have no default set (`null`), and the status for the BGP sessions being editing should not be updated unless I change the status field from `null` to a value.
1. A custom field which uses a JSON value should not be set to `null` if the form is submitted with no value in the value, only if the "set null" value is checked, or I explicitly typed "null" into the filed, not if it s empty/blank.

**Comment by cruse1977** [comment]
Hi James, the status I can take a look at - however there's nothing in netbox-bgp releated to custom fields - this may be an upstream bug and may be better reported there.

**Comment by jwbensley** [comment]
Thanks @cruse1977 for the quick fix!

I will open an "issue" on the main NetBox repo about the custom field.

I have found another bug, the search field in the BGP plugin isn't search the value of custom fields. Should I also open an issue for that under the main NetBox repo too, or under this repo?

**Comment by cruse1977** [comment]
which search page is this on (redacted url/screenshot helpful)

**Comment by cruse1977** [comment]
Yep please raise an issue with that here (we run a 1 issue, 1 PR rule of thumb)

**Comment by jwbensley** [comment]
Thanks!
